[WEB-1450]
thegoodparty/tgp-api pull request #168
Opened 2024-03-19 04:09 UTC by RavenHursT

Updated the create/update endpoints to support md5 unique file names, and to return created/updated resource on response

2024-03-19 04:41 UTC, tomer-tgp requested changes

2024-03-19 04:41 UTC, tomer-tgp commented on api/controllers/topIssues/topIssue/update.js
> +
Don't nest ternary operators. Add a variable for the icon or an if-else statement.

2024-03-19 18:36 UTC, RavenHursT commented on api/controllers/topIssues/topIssue/update.js
> +
https://github.com/thegoodparty/tgp-api/pull/168/commits/9e7c21955d9a06ddde63d8859ee9aef3e978126b

2024-03-20 15:52 UTC, tomer-tgp approved these changes

2024-03-20 15:52 UTC, merged