[WEB-1862] - Stripe API Integration for Pro Plan Flow
thegoodparty/tgp-api pull request #196
Opened 2024-06-14 15:37 UTC by RavenHursT

2024-06-14 21:47 UTC, tomer-tgp requested changes

2024-06-14 21:47 UTC, tomer-tgp commented on api/controllers/campaign/ein-check.js
> +    const { name, ein } = this.req.query;
get these as inputs. Please don't change our patterns

2024-06-14 21:47 UTC, tomer-tgp commented on api/controllers/campaign/ein-check.js
> +    if (!name || !ein || !campaign) {
Mark the inputs as required. then only test for campaign

2024-06-14 21:47 UTC, tomer-tgp commented on api/controllers/payments/portal-session/create.js
> +    const campaign = await Campaign.findOne({ user: this.req.user.id });
I suggest using the helper here, since this logic might change when we have campaign managers.

2024-06-14 21:47 UTC, tomer-tgp commented on api/helpers/campaign/by-user.js
> +      const campaign = await Campaign.findOne({
no. A user can have many campaigns. It is a product requirement, and also a DB design.

2024-06-14 21:47 UTC, tomer-tgp commented on api/helpers/campaign/by-user.js
> +      const campaign = await Campaign.findOne({
right now we have only one, but a user can run twice and have multiple campaigns.

2024-06-14 21:47 UTC, tomer-tgp commented on api/utils/upload-single-file-to-s3.js
> +        'Content-Type': 'application/pdf',
this should probably be a parameter, or rename the file to "upload-pdf"

2024-06-14 21:47 UTC, tomer-tgp commented on api/utils/upload-single-file-to-s3.js
> +        'Content-Type': 'application/pdf',
or is your intention is to allow overriding it with headers?

2024-06-14 22:23 UTC, RavenHursT commented on api/controllers/campaign/ein-check.js
> +    const { name, ein } = this.req.query;
Oh.. wasn't aware that `inputs` _also_ magically grabbed data from the query string, was assuming that was only for stuff in the request body. Mah bad.

2024-06-14 22:44 UTC, RavenHursT commented on api/helpers/campaign/by-user.js
> +      const campaign = await Campaign.findOne({
But the conditional just below it.. doesn't that essentially just do the same thing that `.findOne()` is doing?

`.findOne()` just adds a `LIMIT 1`, and gives you the first result in the list from the DB, right?

Seems a bit odd to do that kind of logic in the DAL instead of just doing it in the DB w/ `LIMIT`, right?

2024-06-14 22:46 UTC, RavenHursT commented on api/utils/upload-single-file-to-s3.js
> +        'Content-Type': 'application/pdf',
Yeah.. `application/pdf` is just the default `Content-Type` here, overridable by `headers` argument

2024-06-14 22:49 UTC, RavenHursT commented on api/controllers/payments/portal-session/create.js
> +    const campaign = await Campaign.findOne({ user: this.req.user.id });
did you mean, “..using **_a_** helper here…“?
Like, suggesting we create an updateIsPro helper, or something?

If did you mean to say “the”.. then, which helper are you referring to? 🤔

2024-06-17 14:40 UTC, tomer-tgp commented on api/helpers/campaign/by-user.js
> +      const campaign = await Campaign.findOne({
yes, right now we return the first one. But if there are multiple campaigns the findOne will fail.

2024-06-17 16:17 UTC, RavenHursT commented on api/helpers/campaign/by-user.js
> +      const campaign = await Campaign.findOne({
@tomer-tgp  `failOne()` fails for `> 1` record?

ChatGPT is saying it just behaves as I mentioned above? 🤔 

<img width="998" alt="image" src="https://github.com/thegoodparty/tgp-api/assets/496983/b9141b5e-5b78-4745-ada8-96137efd2d34">

<img width="770" alt="image" src="https://github.com/thegoodparty/tgp-api/assets/496983/9d33dabc-76b2-4837-8060-e9b146a0cb09">

I'm gonna verify this.. But I really don't think we need to double-check with the following code if there's only 1 record. `.findOne()` handles that for us, and will do so gracefully, even if nothing, or `> 1` record is found:

```javascript
      let campaign = false;
      if (campaigns && campaigns.length > 0) {
        campaign = campaigns[0];
      }
```

2024-06-18 15:07 UTC, merged