Send all users' email addresses to Mailchimp
thegoodparty/tgp-api pull request #23
Opened 2020-10-19 17:50 UTC by webdeveloper001

2020-10-19 21:21 UTC, tomer-tgp requested changes

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +=======
you have merge conflicts here

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +      if(email) {
email is required. You don't need to add `if(email)`

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +      else {
you will never get here

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +        const users = await User.find();
hmmm no...
why would you want to traverse ALL of our userS?

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +          if(users[i].email) {
what is this if testing?

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
> +            console.log(users[i].email)
again, you will never get to this part, but it looks like you wanted to do
```
await User.findOne({email});
```

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
>    description: 'Subscribe email to mailing list on mailChimp.',
I don't understand why we even need this helper.
All it does it calls another helper

2020-10-19 21:21 UTC, tomer-tgp commented on api/helpers/add-email.js
> +      const tgpList = lists.find(list => list.name === 'The Good Party');
you can make this helper more generic by receiving the list name as a required parameter

2020-10-19 21:21 UTC, tomer-tgp commented on api/helpers/add-email.js
> +      console.log(e)
please provide a better error handling. Look at the other ones (report to slack, and add some text before so if we see it on our logs we know where it comes from
Also, you will need to return exits.badRequest (and add it to exits) otherwise, the caller will just wait for the promise to resolve

2020-10-19 21:21 UTC, tomer-tgp commented on api/controllers/subscribe/subscribe-email.js
>   * @help        :: See https://sailsjs.com/documentation/concepts/actions-and-controllers
Did you forget to delete this file?

2020-10-20 08:40 UTC, tomer-tgp requested changes

2020-10-20 08:40 UTC, tomer-tgp commented on api/controllers/seed/temp-task.js
> +          sails.helpers.addEmail(users[i].email);
`await sails.helpers.addEmail(users[i].email);`
you forgot the await

2020-10-20 08:40 UTC, tomer-tgp commented on api/controllers/seed/temp-task.js
> +          sails.helpers.addEmail(users[i].email);
you also need to add the list name

2020-10-20 08:40 UTC, tomer-tgp commented on api/controllers/seed/temp-task.js
> +          sails.helpers.addEmail(users[i].email);
Did you test this? there is no way this worked. the list name is required and the app would have crushed

2020-10-20 08:53 UTC, webdeveloper001 commented on api/controllers/seed/temp-task.js
> +          sails.helpers.addEmail(users[i].email);
sorry I missed that
I just noticed that there are no users on my local.
That's why that API is passed my test.

2020-10-20 09:03 UTC, tomer-tgp requested changes

2020-10-20 09:03 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +      await sails.helpers.addEmail(lowerCaseEmail);
let's wrap this also in a try catch

2020-10-20 09:03 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +      await sails.helpers.addEmail(lowerCaseEmail);
you are missing the list here too

2020-10-20 09:03 UTC, tomer-tgp commented on api/controllers/user/update-user.js
> +        await sails.helpers.addEmail(email);
please wrap this in try catch and you are also missing the list here

2020-10-20 09:10 UTC, tomer-tgp approved these changes

2020-10-20 09:11 UTC, merged