Alter sms campaign slack notification
thegoodparty/tgp-api pull request #269
Opened 2024-10-01 17:36 UTC by oakinh

2024-10-02 13:41 UTC, RavenHursT requested changes

2024-10-02 13:41 UTC, RavenHursT commented on api/controllers/voterData/voterFile/schedule.js
> +      const aiGeneratedScript = sanitizeHtml(campaign.aiContent[script].content, {
Prolly good to put some existential checks here..

2024-10-02 13:41 UTC, RavenHursT commented on api/controllers/voterData/voterFile/schedule.js
> +      if (VoterFileUrl && !isUrl(VoterFileUrl)) { // This WILL filter out localhost URLs, comment out if localhost testing
😬😬😬

There has got to be a better way to do this.. how about adding `&& !VoterFileUrl.startsWith('http:localhost')` to this condition?

2024-10-02 13:41 UTC, RavenHursT commented on api/controllers/voterData/voterFile/schedule.js
> +      if (VoterFileUrl && !isUrl(VoterFileUrl)) { // This WILL filter out localhost URLs, comment out if localhost testing
Also, are you sure this worked? 

You have `VoterFileUrl` here, but on line 57 above the variable is `voterFileUrl`? 🤔

2024-10-02 13:41 UTC, RavenHursT commented on package.json
> +    "@slack/web-api": "^7.5.0",
Did you end up using this? I'm not seeing a `require` for it anywhere? 🤔

2024-10-02 20:03 UTC, RavenHursT approved these changes

2024-10-03 14:45 UTC, tomer-tgp approved these changes

2024-10-03 14:45 UTC, merged