s3 upload / list endpoints for jodit editor
thegoodparty/tgp-api pull request #28
Opened 2020-11-09 21:47 UTC by webdeveloper001

2020-11-10 04:33 UTC, tomer-tgp requested changes

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/upload-image.js
> +    adapter: require('skipper-s3'),
interesting. 
We already have an s3 uploader... Let's consolidate.
look at helpers/s3-uploader.
I don't mind using skipper-s3. Move the require to the top please and the whole function should be a helper. Or just use the existing s3-uploader helper.
Also admin/update-candidate-image should be updated to use the helper.
Please add cache-control: max-age= 12960000

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/upload-image.js
> +    adapter: require('skipper-s3'),
Also, this endpoint should be under /admin folder otherwise, anyone will be able to upload images to our s3. remember we are open source

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/upload-image.js
> +      const image = `https://assets.thegoodparty.org/candidate-info/${uploadedFiles[0].fd}`;
the asset base should come from an env variable so we upload dev assets to dev.

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/uploaded-images.js
> +            baseurl: 'https://assets.thegoodparty.org/candidate-info',
baseUrl should be an env variable (it already exists)

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/uploaded-images.js
> +    Bucket: 'assets.thegoodparty.org',
bucket should be an environment variable

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/uploaded-images.js
> +const AWS = require('aws-sdk');
this should be under /admin

2020-11-10 04:33 UTC, tomer-tgp commented on api/controllers/content/uploaded-images.js
> +  s3Bucket.listObjects({
this should be a helper.

2020-11-10 04:33 UTC, tomer-tgp commented on config/env/development.js
> +      allowRequestHeaders: 'content-type, X-Requested-With, authorization',
why do we need this?
if we do, we need an env variable for it.

2020-11-10 04:33 UTC, tomer-tgp commented on config/routes.js
> +  'POST   /api/v1/content/upload-image': 'content/upload-image',
admin

2020-11-13 11:21 UTC, webdeveloper001 commented on api/controllers/content/upload-image.js
> +    adapter: require('skipper-s3'),
@tomer-tgp , you mean, non-admin users shouldn't be able to upload the image to the s3 bucket?
but not sure if it's possible.
because we have no way to set the header on the upload action for jodit editor.
The only thing I did is to set the upload API end point as their configuration. then they handle upload requests themselves.
so we cannot attach any token there.

2020-11-13 17:23 UTC, tomer-tgp commented on api/controllers/content/upload-image.js
> +    adapter: require('skipper-s3'),
Only admins have access to the front end part. If you move this endpoint under /admin folder, only admins will have access for it.
That is handled in policies here https://github.com/thegoodparty/tgp-api/blob/develop/config/policies.js

2020-11-13 18:33 UTC, tomer-tgp requested changes

2020-11-13 18:33 UTC, tomer-tgp commented on api/controllers/admin/update-candidate-image.js
>    });
can you use our s3 uploader helper here

2020-11-13 18:33 UTC, tomer-tgp commented on api/controllers/admin/update-candidate-image.js
>    });
https://github.com/thegoodparty/tgp-api/blob/develop/api/helpers/s3-uploader.js

2020-11-13 18:33 UTC, tomer-tgp commented on api/helpers/file-uploader.js
> +module.exports = {
We already have an s3-uploader helper
https://github.com/thegoodparty/tgp-api/blob/develop/api/helpers/s3-uploader.js

2020-11-13 18:33 UTC, tomer-tgp commented on config/custom.js
> +  adminEmails: ['blueshark0811@gmail.com'],
this should not be commited.
We can move this to local.js if you want to have it setup separately locally

2020-11-13 18:33 UTC, tomer-tgp commented on config/datastores.js
> +    url: 'postgresql://tgpadmin:myFirst100@localhost:5433/tgp_dev1',
please don't commit these local changes

2020-11-13 18:33 UTC, tomer-tgp commented on config/policies.js
> +  'admin/upload-image': true,
no no
you just made it public.
remove these two lines and keep the admin endpoints for admin only

2020-11-13 18:33 UTC, tomer-tgp commented on package.json
> +    "start": "cross-env NODE_ENV=production nodemon app.js",
nope.
npm start is for production only.
You should use `npm run dev` locally.
nodemon is not available on prod and should not be used on prod.

2020-11-16 10:10 UTC, tomer-tgp approved these changes

2020-11-16 10:10 UTC, merged