Share image issue
thegoodparty/tgp-api pull request #34
Opened 2021-03-02 11:31 UTC by webdeveloper001

2021-03-02 19:10 UTC, tomer-tgp requested changes

2021-03-02 19:10 UTC, tomer-tgp commented on api/controllers/admin/update-candidate.js
>                      id,
the new candidate doesn't have chamber like that

2021-03-02 19:10 UTC, tomer-tgp commented on api/controllers/user/ranking/rank-candidate.js
rank candidate is deprecated

2021-03-02 19:10 UTC, tomer-tgp commented on api/controllers/admin/update-candidate.js
>                      id,
this is the wrong file...
this is where you need to trigger the changes
https://github.com/thegoodparty/tgp-api/blob/develop/api/controllers/newCandidates/update.js

2021-03-02 21:53 UTC, tomer-tgp requested changes
Looks good, just a few minor changes

2021-03-02 21:53 UTC, tomer-tgp commented on api/controllers/newCandidates/update.js
> +  async fn(inputs, exits) {
revert to `fn: async function(inputs, exits) {`

2021-03-02 21:53 UTC, tomer-tgp commented on api/controllers/newCandidates/update.js
> +      if (oldCandidate.data && updatedCandidate.data && oldCandidate.data.candidateUpdates != updatedCandidate.data.candidateUpdates) {
`!==` instead of `!=`
Also let's move all this new logic to a function with a meaningful name like "notifySupporterForUpdates"

2021-03-03 01:32 UTC, talmog approved these changes

2021-03-03 01:33 UTC, merged