fried joined email trigger
thegoodparty/tgp-api pull request #45
Opened 2021-03-23 09:25 UTC by webdeveloper001

2021-03-23 16:58 UTC, tomer-tgp requested changes

2021-03-23 16:58 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +          console.log(referrerUser);
remove logs

2021-03-23 16:58 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +          const ln = name.split(' ').length > 0 && name.split(' ')[1];
change to firstName and lastName (meaningful variable names)

2021-03-23 16:58 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +          const subject = `${ln ? `${fn} ${ln[0]}.` : fn} has joined your Good Party crowd-voting crew`;
lets move this `ln ? `${fn} ${ln[0]}.` : fn` logic to a variable because you are using it multiple times

2021-03-23 16:58 UTC, tomer-tgp commented on api/controllers/entrance/register.js
> +                      text-decoration: none;
I am not sure linear gradient will work on most email server

2021-03-23 17:05 UTC, webdeveloper001 commented on api/controllers/entrance/register.js
> +                      text-decoration: none;
hmmm
let's see how it's working if you don't mind.
we should use background image once we find out some issues regarding this linear-gradient.

2021-03-24 07:56 UTC, tomer-tgp approved these changes

2021-03-24 07:56 UTC, merged